/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 40cf763c071814d6e015363ce2bd56cf)
interface __BaseEnv_CloudflareEnv {
	DOCUMENTS: R2Bucket;
	DB: D1Database;
	BROWSER: BrowserRun;
	GEMINI_MODEL: string;
	VERTEX_PROJECT_ID: string;
	VERTEX_LOCATION: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "VERTEX_PROJECT_ID" | "VERTEX_LOCATION">> {}
}
