/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 948c0894bb60c1ee8cea95075620ecd6)
interface __BaseEnv_CloudflareEnv {
	DOCUMENTS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	GOOGLE_API_KEY: string;
	GEMINI_MODEL: string;
	NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string;
	TREMENDOUS_BASE_URL: string;
	TREMENDOUS_API_KEY: string;
	TREMENDOUS_CAMPAIGN_ID: string;
	TREMENDOUS_FUNDING_SOURCE_ID: string;
	TREMENDOUS_WEBHOOK_ID: string;
	TREMENDOUS_WEBHOOK_URL: string;
	TREMENDOUS_WEBHOOK_SECRET: string;
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	DOCUSEAL_BASE_URL: string;
	DOCUSEAL_SIGN_URL: string;
	NEXT_PUBLIC_DOCUSEAL_EMBED_HOST: string;
	DOCUSEAL_TEMPLATE_ID: string;
	DOCUSEAL_API_TOKEN: string;
	DOCUSEAL_WEBHOOK_URL: string;
	DOCUSEAL_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_API_KEY" | "GEMINI_MODEL" | "NEXT_PUBLIC_CLERK_SIGN_IN_URL" | "NEXT_PUBLIC_CLERK_SIGN_UP_URL" | "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL" | "NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL" | "TREMENDOUS_BASE_URL" | "TREMENDOUS_API_KEY" | "TREMENDOUS_CAMPAIGN_ID" | "TREMENDOUS_FUNDING_SOURCE_ID" | "TREMENDOUS_WEBHOOK_ID" | "TREMENDOUS_WEBHOOK_URL" | "TREMENDOUS_WEBHOOK_SECRET" | "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY" | "DOCUSEAL_BASE_URL" | "DOCUSEAL_SIGN_URL" | "NEXT_PUBLIC_DOCUSEAL_EMBED_HOST" | "DOCUSEAL_TEMPLATE_ID" | "DOCUSEAL_API_TOKEN" | "DOCUSEAL_WEBHOOK_URL" | "DOCUSEAL_WEBHOOK_SECRET">> {}
}
