/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 3393ac536dbe6dfbc78e7137218c1b73)
interface __BaseEnv_CloudflareEnv {
	DOCUMENTS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	BROWSER: BrowserRun;
	ASSETS: Fetcher;
	TREMENDOUS_BASE_URL: "https://api.tremendous.com/api/v2";
	TREMENDOUS_FUNDING_SOURCE_ID: "BALANCE";
	GEMINI_MODEL: string;
	NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string;
	NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string;
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	VERTEX_PROJECT_ID: string;
	VERTEX_LOCATION: string;
	GCP_WIF_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TREMENDOUS_BASE_URL" | "TREMENDOUS_FUNDING_SOURCE_ID" | "GEMINI_MODEL" | "NEXT_PUBLIC_CLERK_SIGN_IN_URL" | "NEXT_PUBLIC_CLERK_SIGN_UP_URL" | "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL" | "NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL" | "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY" | "VERTEX_PROJECT_ID" | "VERTEX_LOCATION" | "GCP_WIF_PRIVATE_KEY">> {}
}
